#
# Copyright Â© ${year} ${owner} (${email})
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: joylive-demo-springcloud2021-gateway
    x-live-enabled: "true"
  name: joylive-demo-springcloud2021-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joylive-demo-springcloud2021-gateway
  template:
    metadata:
      labels:
        app: joylive-demo-springcloud2021-gateway
        x-live-enabled: "true"
    spec:
      containers:
        - env:
            - name: CONFIG_LIVE_SPACE_API_TYPE
              value: multilive
            - name: CONFIG_LIVE_SPACE_API_URL
              value: http://api.live.local/v1
            - name: CONFIG_LIVE_SPACE_API_HEADERS
              value: pin=demo
            - name: CONFIG_SERVICE_API_TYPE
              value: jmsf
            - name: CONFIG_SERVICE_API_URL
              value: http://api.jmsf.local/v1
            - name: LIVE_LOG_LEVEL
              value: info
            - name: CONFIG_LANE_ENABLED
              value: "false"
            - name: NACOS_ADDR
              value: nacos-server.nacos.svc:8848
            - name: NACOS_USERNAME
              value: nacos
            - name: NACOS_PASSWORD
              value: nacos
            - name: APPLICATION_NAME
              value: springcloud2021-gateway
            - name: APPLICATION_SERVICE_NAMESPACE
              value: default
            - name: APPLICATION_LOCATION_REGION
              value: region1
            - name: APPLICATION_LOCATION_ZONE
              value: zone1
            - name: APPLICATION_LOCATION_LIVESPACE_ID
              value: v4bEh4kd6Jvu5QBX09qYq-qlbcs
            - name: APPLICATION_LOCATION_UNIT
              value: unit1
            - name: APPLICATION_LOCATION_CELL
              value: cell1
            - name: APPLICATION_SERVICE_GATEWAY
              value: FRONTEND
          image: hub-vpc.jdcloud.com/jmsf/joylive-demo-springcloud2021-gateway:1.5.0-da16656c
          imagePullPolicy: Always
          name: joylive-demo-springcloud2021-gateway
          ports:
            - containerPort: 8888
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "1Gi"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: springcloud2021-gateway
spec:
  type: NodePort
  ports:
    - port: 8888
      protocol: TCP
      targetPort: http
  selector:
    app: joylive-demo-springcloud2021-gateway

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: joylive-demo-springcloud2021-gateway-gray
    x-live-enabled: "true"
  name: joylive-demo-springcloud2021-gateway-gray
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joylive-demo-springcloud2021-gateway-gray
  template:
    metadata:
      labels:
        app: joylive-demo-springcloud2021-gateway-gray
        x-live-enabled: "true"
    spec:
      containers:
        - env:
            - name: LIVE_LOG_LEVEL
              value: info
            - name: CONFIG_LANE_ENABLED
              value: "false"
            - name: NACOS_ADDR
              value: nacos-server.nacos.svc:8848
            - name: NACOS_USERNAME
              value: nacos
            - name: NACOS_PASSWORD
              value: nacos
            - name: APPLICATION_NAME
              value: springcloud2021-gateway-gray
            - name: APPLICATION_SERVICE_NAMESPACE
              value: default
            - name: APPLICATION_LOCATION_REGION
              value: region2
            - name: APPLICATION_LOCATION_LIVESPACE_ID
              value: v4bEh4kd6Jvu5QBX09qYq-qlbcs
            - name: APPLICATION_LOCATION_UNIT
              value: unit2
            - name: APPLICATION_LOCATION_CELL
              value: cell4
            - name: APPLICATION_SERVICE_GATEWAY
              value: FRONTEND
          image: hub-vpc.jdcloud.com/jmsf/joylive-demo-springcloud2021-gateway:1.5.0-da16656c
          imagePullPolicy: Always
          name: joylive-demo-springcloud2021-gateway-gray
          ports:
            - containerPort: 8888
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "1Gi"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: springcloud2021-gateway-gray
spec:
  type: NodePort
  ports:
    - port: 8888
      protocol: TCP
      targetPort: http
  selector:
    app: joylive-demo-springcloud2021-gateway-gray