apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: brolly
    meta.helm.sh/release-namespace: brolly
  labels:
    app.kubernetes.io/instance: brolly
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: monitor
    app.kubernetes.io/system: brolly
    integration: tpaas-multilive
    inputType: integrations
    release: brolly
  name: tpaas-multilive
spec:
  endpoints:
    - port: prometheus
      interval: 10s

  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector